spring:
    application:
        name: LooksForBooks

    neo4j:
        uri: bolt://localhost:7687
        authentication:
            username: ${DBUSER}
            password: ${DBPSWD}

management:
    endpoints:
        env:
            enabled: true
        mappings:
            enabled: true
        metrics:
            enabled: true
        web:
            exposure:
                include: health, env, mappings, metrics